### ISSUE TITLE
Python: Encoding RGB dicom data through itkwasm-htj2k

### ISSUE THREAD

**Issue by pritamrungta** [InsightSoftwareConsortium/ITKIOOpenJPH#14]
Currently when passing RGB pixel data with shape = [height, width, 3], [encode](https://github.com/InsightSoftwareConsortium/ITKIOOpenJPH/blob/main/src/wasm/python/itkwasm-htj2k/itkwasm_htj2k/encode.py) throws the following error:
```
Unsupported image dimension: 3
Run with --help for more information.
```

Is there a different process to convert such images?

**Comment by thewtex** [comment]
Hi,

Thanks or the report. This was addressed in #18
