### ISSUE TITLE
python: null error check

### ISSUE THREAD

**Issue by pritamrungta** [InsightSoftwareConsortium/ITKIOOpenJPH#19]
The latest release of itkwasm-htj2k==2.2.0 might have added an unintentional bug.

https://github.com/InsightSoftwareConsortium/ITKIOOpenJPH/commit/c07807a0def2f1fe3c07c5a36563c1381f25a839#diff-ed441ea9fb9f6603c942eeec2e9d53f8f10cd0e4ea61fcc3f5ed2bfbf6b011d3L18-R20

While the params above accept None values, the following doesn't and throws error in the given line:
https://github.com/InsightSoftwareConsortium/ITKIOOpenJPH/blob/main/src/wasm/python/itkwasm-htj2k-wasi/itkwasm_htj2k_wasi/encode.py#L89

**Comment by thewtex** [comment]
@pritamrungta thanks for the note!

Addressed in #21 (reverts the addition of `Optional`) and released in 2.3.1.
